server:
  port: 9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    active: dev

  application:
    name: FOOD-CATALOGUE-SERVICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodcataloguedb
    password: test@1234
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect